### ISSUE TITLE
Worldgen options appears on top of "credits and attribution" on 1.19.4

### ISSUE THREAD

**Issue by Vector-Graphics** [PercyDan54/BorderRemover#13] opened 2023-04-21 03:17 UTC
### Type

Game behaviour

### Bug description

Worldgen options appears behind "credits and attribution" on 1.19.4 and is unselectable

### Screenshots or videos

![image](https://user-images.githubusercontent.com/62966659/233532336-99dfa3ed-1f26-484a-b314-31c5fe04332a.png)

### Minecraft Version

1.19.4

**Comment by PercyDan54** [comment] 2023-04-21 12:05
I love how Mojang make refactors even on minor versions

**Comment by PercyDan54** [comment] 2023-04-21 12:31
This is the hacked fix I can done, the problem is I have to move "Done" button down which cause it to overflow (you can still use it with maximised window or fullscreen)
![image](https://user-images.githubusercontent.com/50285552/233636575-7997ce99-e9c9-4a63-9fcf-ced4e3be0314.png)

If you can accept this I'll push the fix

**Comment by Vector-Graphics** [comment] 2023-04-21 18:11
Yes, it's fine. I usually have my gui scale pretty small anyway.

**Comment by Vector-Graphics** [comment] 2023-04-21 18:11
I mean also, shouldn't this be part of the world creation screen rather than the options menu?

**Comment by PercyDan54** [comment] 2023-04-21 23:13
Fixed in release

**Closed as completed by PercyDan54** 2023-04-21 23:13 UTC
